### ISSUE TITLE
fix CI settings 

### ISSUE THREAD

**Issue by raamana** [INCF/niQC#18]
there is an issue with circleCI's deploy key being read-only, so it is unable to deploy the webpages after successful builds.

https://app.circleci.com/pipelines/github/INCF/niQC/124/workflows/7e0a0b58-6f63-48e1-9d9b-702c95b0e73d/jobs/88/steps

follow the manual process and add the keys with write permissions cc @anibalsolon

**Comment by anibalsolon** [comment]
@raamana lets move it to Github Actions WYT?

**Comment by raamana** [comment]
Sure, If you think that makes it easier for us (e.g. reduce maintenance). You've the necessary permissions, right?

**Comment by anibalsolon** [comment]
I have it, yes! I will try to address it today.

**Comment by raamana** [comment]
great, thanks.

**Comment by anibalsolon** [comment]
Done! It is better to keep it here so it is easier to access the logs and it is public.

**Comment by raamana** [comment]
great, awesome! :) how did you fix it?

**Comment by anibalsolon** [comment]
I've moved from CircleCI to Github Actions- Not sure what the issue was with the CircleCI access token, but Github Actions provides easier access to push changes to the repo.

This is the workflow it runs now:
https://github.com/INCF/niQC/blob/master/.github/workflows/deploy.yml
Github makes a token available to use in the workflow using the `${{ secrets.GITHUB_TOKEN }}` variable.

And we can check the logs of the builds here, in case there is any problems: https://github.com/INCF/niQC/actions

**Comment by raamana** [comment]
Oh, ok, cool. Great that it works as we expect few more additions to the resources page soon, and I don't want us to have to poke into them at all! :)

**Comment by raamana** [comment]
Hi @anibalsolon I pushed a new news item via cd89124 but it didn't update the website despite a successful deploy from GitHub actions.. I cleared the cache and reloaded website on few browser but no luck. any idea?

**Comment by anibalsolon** [comment]
@raamana it is there, must just take some time for Github to refresh its own caches.

![image](https://user-images.githubusercontent.com/562525/125320293-2e86f100-e301-11eb-94c6-7f72c331836d.png)

**Comment by raamana** [comment]
great, thanks! perhaps we should remove the CircleCI hook?
